name: Docs from PR

on:
  pull_request:
    types: [closed]

jobs:
  sync-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to docs repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/Rita-Tavares/demo-docs-repo.git
          rsync -av --exclude='.git' ./ demo-docs-repo/
          cd demo-docs-repo
          git add .
          git commit -m "Update docs from PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push
