name: Docs from PR

on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  write-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          repository: Rita-Tavares/demo-docs-repo
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: docs-repo

      - name: Fetch PR diff (authenticated)
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          curl -sSL \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3.diff" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
            -o /tmp/pr.diff
          test -s /tmp/pr.diff || { echo "PR diff is empty"; exit 1; }

      - name: Build docs page (into new-docs/)
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          set -e
          DATE="$(date -u +%Y-%m-%d)"
          # slug from PR title
          SAFE_TITLE="$(echo "$PR_TITLE" | tr ' /' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')"
          FILE="docs-repo/new-docs/${DATE}-${SAFE_TITLE}.md"
          mkdir -p "$(dirname "$FILE")"

          {
            echo "---"
            echo "title: \"$PR_TITLE\""
            echo "description: \"Auto-generated from PR #$PR_NUMBER\""
            echo "---"
            echo
            echo "**PR:** [#$PR_NUMBER]($PR_URL)"
            echo
            if [ -n "$PR_BODY" ]; then
              echo "### Summary"
              echo "$PR_BODY"
              echo
            fi
            echo "### Code changes (unified diff)"
            echo '```diff'
            sed -e 's/\t/  /g' /tmp/pr.diff | sed -e 's/\r$//'
            echo '```'
          } > "$FILE"

      - name: Open PR to docs repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: docs-repo
          base: main
          branch: docs/from-pr-${{ github.event.pull_request.number }}
          title: "Docs: ${{ github.event.pull_request.title }} (PR #${{ github.event.pull_request.number }})"
          body: "Automated docs page generated from PR [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})."
